### ISSUE TITLE
支持，不过有一个问题

### ISSUE THREAD

**Issue by wangwu50** [stulzq/azure-openai-proxy#1]
我也是azure的用户，之前针对https://github.com/Chanzhaoyu/chatgpt-web，用python自己实现了azure的接口，看到这个项目的思路非常好。但看了下代码，应该有个主要问题没解决。
openapi和azure的最大区别是，对于prompt，官方的入参是json数组形式，但azure是一个string。
官方的例子：message=[{"role": "user", "content": prompt}，{"role": "assistant", "content": resp}]
azure的例子：prompt=<|im_start|>user\n prompt\n<|im_end|>\n<|im_start|>assistant\n resp\n<|im_end|>\n
另外azure需要额外设置stop=["<|im_end|>"]
希望能完善，后续如果好用我也切换到这个里面来

**Comment by stulzq** [comment]
你看看我的 README，支持的，你说的接口是 completions，实际上需要的是 chatcompletions

**Comment by stulzq** [comment]
> 我也是azure的用户，之前针对[https://github.com/Chanzhaoyu/chatgpt-web，用python自己实现了azure的接口，看到这个项目的思路非常好。但看了下代码，应该有个主要问题没解决。](https://github.com/Chanzhaoyu/chatgpt-web%EF%BC%8C%E7%94%A8python%E8%87%AA%E5%B7%B1%E5%AE%9E%E7%8E%B0%E4%BA%86azure%E7%9A%84%E6%8E%A5%E5%8F%A3%EF%BC%8C%E7%9C%8B%E5%88%B0%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E7%9A%84%E6%80%9D%E8%B7%AF%E9%9D%9E%E5%B8%B8%E5%A5%BD%E3%80%82%E4%BD%86%E7%9C%8B%E4%BA%86%E4%B8%8B%E4%BB%A3%E7%A0%81%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%9C%89%E4%B8%AA%E4%B8%BB%E8%A6%81%E9%97%AE%E9%A2%98%E6%B2%A1%E8%A7%A3%E5%86%B3%E3%80%82) openapi和azure的最大区别是，对于prompt，官方的入参是json数组形式，但azure是一个string。 官方的例子：message=[{"role": "user", "content": prompt}，{"role": "assistant", "content": resp}] azure的例子：prompt=<|im_start|>user\n prompt\n<|im_end|>\n<|im_start|>assistant\n resp\n<|im_end|>\n 另外azure需要额外设置stop=["<|im_end|>"] 希望能完善，后续如果好用我也切换到这个里面来

直接切换吧（狗头）

**Comment by stulzq** [comment]
我自己已经在用了，完美适配，和官方接口没有任何水土不服

**Comment by wangwu50** [comment]
azure也支持chatcompletions了？

**Comment by wangwu50** [comment]
赞，我试试，我之前针对completions改了一版，挺痛苦的

**Comment by diemus** [comment]
model的映射方式可以考虑该一下，支持多种，因为azure那边每个模型都得自己部署

**Comment by stulzq** [comment]
> model的映射方式可以考虑该一下，支持多种，因为azure那边每个模型都得自己部署

这个可以考虑，目前是通过 AZURE_OPENAI_DEPLOY 来配置模型的，发送过来的 model 参数实际上是无用的。

**Comment by diemus** [comment]
我直接写了一个，支持代理所有模型和接口，有兴趣可以看看：https://github.com/diemus/azure-openai-proxy
