### ISSUE TITLE
建議在 proxy 中直接維護 mapping 表，不需要再加參數

### ISSUE THREAD

**Issue by sujunmin** [stulzq/azure-openai-proxy#10]
Hi,

很棒的專案。

建議在 proxy 中直接維護 mapping 表，在  azure 建立 deployment model 的名字就按照固定對應去修改即可，沒對應到的會固定拋錯 (DeploymentNameFotFound)。
或是能多個 mapping 在設定裏面 。

謝謝～

**Comment by piwawa** [comment]
感觉mapping都不需要，Azure官方给的示例代码都是直接传入deployment model的名字，都不需要model原名

**Comment by stulzq** [comment]
作为 Proxy，接收的是 OpenAI API 标准的请求，传过来的都是**标准**的模型名称，但是 Azure 有1个部署模型名称的概念，用户是可以自定义的，不能让 Proxy 去约束用户必须按照指定的规则建立部署模型名称

**Comment by stulzq** [comment]
其实有1个默认的转换，也可以狭义的理解为默认 MAPPING 表，将 OpenAI 模型名称去掉点号 `.` 建立 Azure 部署模型名称就可以自动映射，不用配置 MAPPING

**Comment by stulzq** [comment]
比如 gpt-3.5-turbo 默认映射为 gpt-35-turbo

**Comment by sujunmin** [comment]
太棒了! @stulzq 現在已經實作這個默認了嗎？

**Comment by stulzq** [comment]
> 太棒了! @stulzq 現在已經實作這個默認了嗎？

是的，你可以直接使用

**Comment by sujunmin** [comment]
> 作为 Proxy，接收的是 OpenAI API 标准的请求，传过来的都是**标准**的模型名称，但是 Azure 有1个部署模型名称的概念，用户是可以自定义的，不能让 Proxy 去约束用户必须按照指定的规则建立部署模型名称

對的，但是通常如果是openai 來的用戶，應該會自然適應 openai 的 model name，如果在 azure 亂取名字反而會看不懂，我自己是會取一樣的名字～

**Comment by sujunmin** [comment]
> > 太棒了! @stulzq 現在已經實作這個默認了嗎？
> 
> 是的，你可以直接使用

太好了，那我 close 這個 issue (建議也寫在 readme 中)
