### ISSUE TITLE
请求合并chatgpt web和该项目的docker镜像！

### ISSUE THREAD

**Issue by piwawa** [stulzq/azure-openai-proxy#11]
能不能直接把代理加到chatgpt web原始镜像中，直接一个容器启动，同时跑两个容器有些冗余，不爽

**Comment by jiaopengzi** [comment]
同求

**Comment by stulzq** [comment]
可以 今天有时间我弄一弄

**Comment by debugAllTheTime** [comment]
嘤嘤嘤，催更

**Comment by peizh** [comment]
冒昧在这个 issue 问个问题，单独启动 azure-openai-proxy 验证正常，但是用 docker-compose 把两个容器一起启动，chatgpt-web 那边提示网页端对话窗口全是返回INVALID_URL，看服务器端 log 提示TypeError [ERR_INVALID_URL]: Invalid URL。但是看 log 里的 URL 又都是对的，proxy 转换也是成功的，是不是 chenzhaoyu94/chatgpt-web 最新镜像有修改……
