### ISSUE TITLE
大佬，我配置的有问题吗？

### ISSUE THREAD

**Issue by itxtl** [stulzq/azure-openai-proxy#12]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/28883383/230789942-5503d4fc-ee1d-4182-b413-906b5f9d67e0.png">
<img width="915" alt="image" src="https://user-images.githubusercontent.com/28883383/230789957-081276a5-6bbe-44e0-a2d3-acba484b1143.png">

**Comment by itxtl** [comment]
能拉个群讨论不

**Comment by stulzq** [comment]
chatgpt-web 这个镜像需要2个配置：

`OPENAI_API_KEY ` 设置为 Azure OpenAI 秘钥
`OPENAI_API_BASE_URL ` 设置为 Proxy 地址

**Comment by itxtl** [comment]
Proxy 这个可以直接部署在 railway 这些服务器上吗？

**Comment by stulzq** [comment]
railway 我没部署过，README 有提供 docker compose 你可以直接使用或者参考。

**Comment by itxtl** [comment]
OPENAI_API_BASE_URL 这个要带你的默认的端口吧，比如这样 ip: port

**Comment by stulzq** [comment]
> OPENAI_API_BASE_URL 这个要带你的默认的端口吧，比如这样 ip: port

对的

**Comment by itxtl** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/28883383/230831958-d9ac360b-4f05-4ccb-9e9c-2d06531c6cb6.png">
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/28883383/230831959-3a8ee3ed-c004-4280-a16b-17528cd7e1f8.png">
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/28883383/230831957-ffc099f3-d783-41f4-9a78-b97daece4c20.png">
启动是成功的，telnet 命令也可以，但是访问不了

**Comment by itxtl** [comment]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/28883383/230832080-b08e98bd-b98e-4383-ab01-094d06887372.png">
配置也是按照您说的～

**Comment by stulzq** [comment]
建议你直接用 docker compose 吧，你这配置有问题。

**Comment by stulzq** [comment]
让你设置 proxy 的地址，你怎么设置了 chatgpt-web的地址

**Comment by stulzq** [comment]
设置地址要加上 http:// ，注意末尾不要跟斜杠

<img width="564" alt="image" src="https://user-images.githubusercontent.com/13200155/230832735-36d8a57e-b475-41c6-9e49-d1316f2d6b44.png">

**Comment by stulzq** [comment]
chatgpt-web 这个项目设置 BASE URL （Proxy 的端口 和 IP）让他能够调用 Proxy，Proxy 的端口是 8080

**Comment by itxtl** [comment]
![Uploading image.png…]()
大佬，是我的问题，我将模型名字用成我的了，不过为啥打印机效果没有了

**Comment by itxtl** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/28883383/230910791-d04a2c0d-70e6-4826-bd3f-6b1c172c2247.png">

Uploading image.png…
大佬，是我的问题，我将模型名字用成我的了，不过为啥打印机效果没有了

**Comment by stulzq** [comment]
这个问题建议你去隔壁问一下 chatgpt-web。我能保证 Proxy 没问题，因为流接口是我专门测试了的，并且我自己用也是一直没问题的。
