### ISSUE TITLE
支持gpt4

### ISSUE THREAD

**Issue by zhangzhaorui** [stulzq/azure-openai-proxy#15]
hi 老师您好，我现在申请了azure上边的gpt4的模型试用，但是目前配置完成之后报错，docker-compose配置文件如下
version: '3'

services:
  chatgpt4-web:
    #image: chenzhaoyu94/chatgpt-web
    image: chenzhaoyu94/chatgpt-web:latest
    ports:
      - 3003:3002
    environment:
      OPENAI_API_KEY: xxxxxxx
      OPENAI_API_BASE_URL: http://10.18.72.88:8086
      AUTH_SECRET_KEY: ""
      MAX_REQUEST_PER_HOUR: 1000
      TIMEOUT_MS: 60000
    depends_on:
      - azure4-openai
    links:
      - azure4-openai
    networks:
      - chatgpt4-ns

  azure4-openai:
    image: ishadows/azure-openai-proxy
    ports:
      - 8086:8080
    environment:
      AZURE_OPENAI_ENDPOINT: https://xxxxxxx.openai.azure.com/
      AZURE_OPENAI_MODEL_MAPPER: gpt-4=zzr_test
      AZURE_OPENAI_API_VER: 2023-03-15-preview
    networks:
      - chatgpt4-ns

networks:
  chatgpt4-ns:
    driver: bridge

报错信息：
![image](https://user-images.githubusercontent.com/18107299/232438482-2d815372-24d2-43c7-a47f-f6db90c987ea.png)

proxy的报错：
[GIN] 2023/04/17 - 08:33:45 | 404 |       1.018µs |      172.27.0.1 | GET      "/v1/dashboard/billing/usage?start_date=2023-04-01&end_date=2023-04-30"
2023/04/17 08:34:11 proxying request [gpt-3.5-turbo] /v1/chat/completions -> https://.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-03-15-preview
[GIN] 2023/04/17 - 08:34:14 | 404 |  3.201908308s |      172.27.0.1 | POST     "/v1/chat/completions"

请教您一下 这个问题怎么解决

**Comment by stulzq** [comment]
chatgpt-web 这个容器配置下环境变量 `OPENAI_API_MODEL: gpt-4`

**Comment by zhangzhaorui** [comment]
收到 大佬 我试一下

**Comment by zhangzhaorui** [comment]
问题已经解决了 ，大佬牛逼 感谢

**Comment by twfeiyu** [comment]
> OPENAI_API_MODEL: gpt-4

感谢,我也碰到这个问题,修改之后测试,已解决了.
