### ISSUE TITLE
[OpenAI] 错误的网关 |  Bad Gateway

### ISSUE THREAD

**Issue by partitionlcj** [stulzq/azure-openai-proxy#17]
老师你好，求教
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/57903465/232456176-2ad08ed3-f071-431f-8521-489ae6ea0e9d.png">

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/57903465/232456459-be3632d4-377c-48a3-b9b1-7b9aad7690fd.png">

<img width="634" alt="image" src="https://user-images.githubusercontent.com/57903465/232466250-0ddb3342-9b57-48d5-aae5-519ede7d55fe.png">

报这个错，求教这是我哪里设置错了么？

**Comment by PeterDaveHello** [comment]
`http: proxy error: dial tcp 20.62.129.182:443: i/o timeout` @@

**Comment by stulzq** [comment]
我暂时没看出头绪 emmm

**Comment by debugAllTheTime** [comment]
OPENAI API BASE URL:后面的IP设置成   宿主机IP:8080

**Comment by partitionlcj** [comment]
> OPENAI API BASE URL:后面的IP设置成 宿主机IP:8080

用 宿主机IP，localhost, 127.0.0.1都试过了，不work

**Comment by stulzq** [comment]
有点怀疑是不是你的 docker 环境的网络问题了

**Comment by partitionlcj** [comment]
> 有点怀疑是不是你的 docker 环境的网络问题了

大佬这个应该怎么排查呢？

**Comment by partitionlcj** [comment]
我本机没问题，一部署服务器就这样了emmm

**Comment by MMMMMz** [comment]
我也遇到了这个问题，不知道题主最后怎么解决的呀？ @partitionlcj ，换成localhost, 127.0.0.1或者宿主机IP后都显示Invalid URL

**Comment by partitionlcj** [comment]
@MMMMMz 应该就是docker网络问题，我们服务器docker是统一做了设置，没有docker0网络，我也没去细研究，我本地使用没问题
