### ISSUE TITLE
what's AZURE_OPENAI_MODEL_MAPPER?

### ISSUE THREAD

**Issue by Moss-qc** [stulzq/azure-openai-proxy#2]
the proxy doesn't work in my azure's server.

If I use openai key, it works fine, but if I use azure key after proxy, it doesn't work.

![image](https://user-images.githubusercontent.com/129234938/228581412-9be1001f-f1cb-4360-88cd-71f23b2ec27a.png)

I think that problem is in the yaml file.
![image](https://user-images.githubusercontent.com/129234938/228582910-cc3631f0-1c5a-427f-ad03-e45e9f0f3a3f.png)

what's AZURE_OPENAI_MODEL_MAPPER? How can I get it? Would u give me an example? Thanks a lot!

**Comment by stulzq** [comment]
AZURE_OPENAI_MODEL_MAPPER is a mapping from Azure OpenAI deployed model names to official OpenAI model names.

AZURE_OPENAI_MODEL_MAPPER: <Azure OpenAI deployment model name>=<OpenAI Model Name>

example:

AZURE_OPENAI_MODEL_MAPPER: gpt-35=gpt-3.5-turbo

**Comment by Moss-qc** [comment]
solved my problem, thanks!

**Comment by stulzq** [comment]
ok
