### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by quzard** [stulzq/azure-openai-proxy#20]
azure-openai-gpt4  | 2023/04/18 04:49:37 [Recovery] 2023/04/18 - 04:49:37 panic recovered:
azure-openai-gpt4  | net/http: abort Handler
azure-openai-gpt4  | net/http/httputil/reverseproxy.go:363 (0x30666f)
azure-openai-gpt4  | github.com/stulzq/azure-openai-proxy/azure/proxy.go:65 (0x31cffb)
azure-openai-gpt4  | github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x30dc7b)
azure-openai-gpt4  | github.com/gin-gonic/gin@v1.9.0/recovery.go:102 (0x30dc5c)
azure-openai-gpt4  | github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x30cf1b)
azure-openai-gpt4  | github.com/gin-gonic/gin@v1.9.0/logger.go:240 (0x30cef8)
azure-openai-gpt4  | github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x30c01f)
azure-openai-gpt4  | github.com/gin-gonic/gin@v1.9.0/gin.go:620 (0x30bd08)
azure-openai-gpt4  | github.com/gin-gonic/gin@v1.9.0/gin.go:576 (0x30ba5b)
azure-openai-gpt4  | net/http/server.go:2947 (0x22246b)
azure-openai-gpt4  | net/http/server.go:1991 (0x21e9f3)
azure-openai-gpt4  | runtime/asm_arm64.s:1172 (0x75343)

**Comment by quzard** [comment]
> 有请求的信息吗，我复现下

概率性出现

**Comment by PeterDaveHello** [comment]
I found that long prompt will got the error frequently

**Comment by piwawa** [comment]
怎么搞得Azure GPT4?

**Comment by stulzq** [comment]
可以看下这个：https://www.cnblogs.com/stulzq/p/17285989.html
0

**Comment by wzhliang** [comment]
I am using the `llm` package and seeing this as well. It looks like creating a streaming request will cause this.
I am guessing the following line 

`	req.Body = io.NopCloser(bytes.NewBuffer(body))
`
But not sure.
