### ISSUE TITLE
proxy返回404  Not Found

### ISSUE THREAD

**Issue by keshushu-com** [stulzq/azure-openai-proxy#21]
界面返回这个
ChatGPT error 404: {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

查看proxy日志，提示404 Not Found
请求的 /v1/chat/completions 这个接口

**Comment by stulzq** [comment]
DeploymentNotFound 你可能需要设置下 MAPPING，参考这个 https://github.com/stulzq/azure-openai-proxy/issues/10

**Comment by keshushu-com** [comment]
> DeploymentNotFound 你可能需要设置下映射，参考这个#10

已经解决，少配置一个OPENAI_API_MODEL  默认是走的3.5 配置的是4
