### ISSUE TITLE
无法使用GPT-4

### ISSUE THREAD

**Issue by jebouruama** [stulzq/azure-openai-proxy#23]
我尝试使用azure openai gpt-4部署模式时，报错。

docker-compose.yml 配置为：
AZURE_OPENAI_MODEL_MAPPER: gpt-4=gpt4

启动后mapper中有两个键值对（第一个是默认值，第二个是yml中设定的值）：如下图
![CleanShot 2023-04-20 at 20 31 45@2x](https://user-images.githubusercontent.com/44332338/233367362-9cc9a8c9-7522-4207-8c53-fc10950c8742.png)

开始对话报错如下：
undefined
[ChatGPT error 404: {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}]

多次尝试发现AZURE_OPENAI_MODEL_MAPPER如果设置为非”gpt-3.5-turbo“键，则最终mapper中会添加一个键值对，而不是替换默认第一个键值对，而程序默认使用第一个键值对的值，该值在我的azure资源中没有相应的资源名称，因此报错资源不存在。
如果将model mapper设置为：AZURE_OPENAI_MODEL_MAPPER: gpt-3.5-turbo=gpt4，则仅有一个键值对，可以正常对话，但看程序输出使用的还是gpt-3.5模型，而不是gpt-4

**Comment by stulzq** [comment]
#15

**Comment by jebouruama** [comment]
多谢指点，终于搞明白了。提个小建议，在说明文档的docker-compose.yml中添加OPENAI_API_MODEL环境变量的设置就更清晰了。

**Comment by stulzq** [comment]
好的 我更新到 README

**Comment by drxmy** [comment]
您好，想问一下azure的gpt4容易申请吗？

**Comment by jebouruama** [comment]
> 您好，想问一下azure的gpt4容易申请吗？

我们同时是azure中国和azure global的企业用户，申请时请微软的人内部打了招呼（也不知道是否管用），等了大约2周通过的。普通个人用户不太清楚是不是获批时间会比较长。
