### ISSUE TITLE
大佬，如果是Nginx 代理的方式，然后再配置通过域名映射，是否需要关闭 proxy_buffering ，但是我试了不成功，求教！

### ISSUE THREAD

**Issue by itxtl** [stulzq/azure-openai-proxy#24]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/28883383/233840644-e246af7f-f0d4-4697-afcf-9bae14b861a2.png">

**Comment by stulzq** [comment]
我自己没配置过 nginx，用的 Azure Front Door

**Comment by itxtl** [comment]
嗯嗯，好的，谢谢，后面我通过cf的方式弄成了https 这种方式能成功
