### ISSUE TITLE
大神，如果是桌面版本的这种，代理有什么不一样吗？貌似会现在加载不成功

### ISSUE THREAD

**Issue by itxtl** [stulzq/azure-openai-proxy#25]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/28883383/234202635-5e52d168-b562-4405-8e9d-4dd835d062e2.png">

**Comment by stulzq** [comment]
代理没问题的，你自己找一下这个 desktop 应用设置一下 API Server 地址为 Proxy 地址

**Comment by itxtl** [comment]
https://github.com/Bin-Huang/chatbox/releases

我试了几个都不行，大神有时间可以下载这个试试，它支持mac和windows

**Comment by itxtl** [comment]
因为不会抓包这些，本来想试试，折腾好久了

**Comment by itxtl** [comment]
cf 代理的可以，但是使用您这个项目 openai 转 azure-openai 的这种方式就不行

**Comment by stulzq** [comment]
提供一下 proxy 的日志我看看

**Comment by itxtl** [comment]
<img width="1586" alt="image" src="https://user-images.githubusercontent.com/28883383/234214345-88134c82-964f-41fa-b80a-1425756bbe61.png">

**Comment by itxtl** [comment]
上面是成功的日志，下面是失败的日志吧～

**Comment by stulzq** [comment]
知道原因了 等我解决下

**Comment by vindia9** [comment]
您好，chatbox遇到同样的问题。

docker images:  image: stulzq/azure-openai-proxy:v1.3.2
chatbox: 0.4.0

<img width="605" alt="image" src="https://user-images.githubusercontent.com/9072630/234293721-25a4b8f8-900a-4583-a15a-1f55bf0001c8.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/9072630/234294763-509aeb0a-4abe-456a-ab30-d876e5a8561b.png">

**Comment by zhuyaguang** [comment]
> cf 代理的可以，但是使用您这个项目 openai 转 azure-openai 的这种方式就不行

Cf 代理怎么配置，大佬有教程吗

**Comment by stulzq** [comment]
下载下来试了，没看出头绪来。OPTIONS 请求我也弄正确了，但就是不继续请求了

**Comment by itxtl** [comment]
额，大佬昨天发现的原因是啥。。

**Comment by itxtl** [comment]
是桌面端端请求机制不一样吗？我试了 OpenCat 这个是可以的

**Comment by stulzq** [comment]
应该是ChatBox 的什么机制

**Comment by itxtl** [comment]
我把这个问题问下原作者看下能不能回复一下我们。。

**Comment by stulzq** [comment]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/13200155/234531194-1d2bd16e-e304-4371-af24-597cfdb5571f.png">
解决了 等我 Release

**Comment by stulzq** [comment]
等打包完成用 v1.3.3 版本就行 ，已测试 GPT-3.5-turbo 和 GPT-4

**Comment by stulzq** [comment]
@zhuyaguang @vindia9

**Comment by vindia9** [comment]
太好了，感谢作者，马上开测！

**Comment by itxtl** [comment]
嗯嗯，好的，镜像也一起更新一下吧。。

**Comment by stulzq** [comment]
镜像 tag 用 v1.3.3， latest 还在打包，我已经用上了嘿嘿

**Comment by vindia9** [comment]
可以了，谢谢 ～

<img width="675" alt="image" src="https://user-images.githubusercontent.com/9072630/234534626-ff704182-ec30-4dad-98d3-fc37ac91d1c6.png">

**Comment by trader-tsang** [comment]
![image](https://user-images.githubusercontent.com/128910472/235046819-fe8ee198-0c7f-472b-b38f-341d2daf9ebb.png)
请教一下你们是怎么设置的啊？ 只设置这个API host么，我用chanzhaoyu/chatgptweb能正常访问，但chatbox显示failed to fetch. proxy都没有收到请求。
