### ISSUE TITLE
docker-compose起来后，网页上用起来没有打字效果

### ISSUE THREAD

**Issue by liuzoxan** [stulzq/azure-openai-proxy#26]
你自已用的时候有打字效果吗？

**Comment by yk271** [comment]
貌似是 Azure 的问题，我之前有打字效果，今天突然没了。Azure OpenAI Studio 上测试也一样。

**Comment by hanjianshuo** [comment]
我这里也是刚开始有打字效果，发了几条信息就没有了，docker里用了nginx么？

**Comment by liuzoxan** [comment]
我觉得打字效果还挺重要的，不然等几百字的全文要等好久，不习惯的用户以为后台Timeout了。希望有人能一起看看。

**Comment by liuzoxan** [comment]
> 我这里也是刚开始有打字效果，发了几条信息就没有了，docker里用了nginx么？

应该没有吧

**Comment by liuzoxan** [comment]
> 

我今天也测试一下azure

**Comment by stulzq** [comment]
你自己浏览器 F12 看看数据包就行，Proxy 不对让打字机效果丢失的，适配了流接口的

**Comment by stulzq** [comment]
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/13200155/235048111-f4e556b5-2657-40df-aa3b-ebd39291587d.png">

**Comment by ytdu** [comment]
遇到同样的问题。是一段一段出的，而不是一个词一个词出的。
直接localhost:8080调用api也是一样，一段一段地蹦出来。
但不确定是azure那边的原因还是这边的原因。
感觉像是什么位置有buffer，buffer满了才出。

**Comment by stulzq** [comment]
我确定 Proxy 没问题，可能是网络原因吧，流接口本来就是一段一段返回的

**Comment by liuzoxan** [comment]
> 我确定 Proxy 没问题，可能是网络原因吧，流接口本来就是一段一段返回的

我测试了azure playground确实也是一段一段返回的。

**Comment by stulzq** [comment]
<img width="984" alt="image" src="https://user-images.githubusercontent.com/13200155/235075643-d2e34c37-9285-4ff1-ae17-67e45db1bda8.png">

**Comment by yk271** [comment]
https://user-images.githubusercontent.com/29210205/235081501-9e5c4e61-e946-45be-8d19-e8b8cebcbdfc.mp4

应该是 Azure 的问题

**Comment by ytdu** [comment]
我后面也测了直接请求azure，应该是azure的问题。

> 遇到同样的问题。是一段一段出的，而不是一个词一个词出的。 直接localhost:8080调用api也是一样，一段一段地蹦出来。 但不确定是azure那边的原因还是这边的原因。 感觉像是什么位置有buffer，buffer满了才出。

**Comment by VectorZhao** [comment]
确实没有打字机效果。。。。。。az搬也不搬完整，打字机都扔了

**Comment by paulcx** [comment]
应该不是Azure的问题？例如：[https://github.com/openai-translator/openai-translator/issues/594](https://github.com/openai-translator/openai-translator/issues/594)

**Comment by VectorZhao** [comment]
我发现openai translator这个软件/插件，配置好azure的openai，确实是可以打字机效果输出。但是他应该不是流式输出，应该是等azure的openai问题都回答完毕后，再把所有内容打字机效果输出。
openai的api是可以流式输出。

**Comment by shunyue1320** [comment]
确实是一段一段返回的。

**Comment by onlyLTY** [comment]
> 你自己浏览器 F12 看看数据包就行，Proxy 不对让打字机效果丢失的，适配了流接口的

proxy是流返回，但是前端显示就是一段一段。可能还是哪里出bug了

**Comment by VectorZhao** [comment]
https://github.com/haibbo/cf-openai-azure-proxy

这个项目

**Comment by qq516249940** [comment]
实现打印机模式：
Azure OpenAI Service's 回复是一段一段回复的
返回给客户端的时候， 本项目拆出一条条的消息, 依次给， 达到打印机模式

> https://github.com/haibbo/cf-openai-azure-proxy
> 
> 这个项目

**Comment by stulzq** [comment]
> https://github.com/haibbo/cf-openai-azure-proxy

看过了，响应的时候手动加了延迟，我自己在本地也实现了感觉不太好。目前昨天有小伙伴说是因为 Azure OpenAI 加了 Content Filter，可以申请取消。昨天已经提交了等审批后看看效果

**Comment by qixiaobo** [comment]
> > https://github.com/haibbo/cf-openai-azure-proxy
> 
> 看过了，响应的时候手动加了延迟，我自己在本地也实现了感觉不太好。目前昨天有小伙伴说是因为 Azure OpenAI 加了 Content Filter，可以申请取消。昨天已经提交了等审批后看看效果
以前好像没问题 最近处理的是吧 就是说azure又加了内容审核对吧

**Comment by qixiaobo** [comment]
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/content-filter

**Comment by kongpf8848** [comment]
Azure OpenAI接口Stream输出是一段一段返回的，但没有OpenAI接口返回那么流畅自然，反映到UI上就是卡卡的，很突兀。需要在代码里加延迟，如每隔50毫秒输出一段，可参考项目[https://github.com/kongpf8848/azure-openai-proxy](https://github.com/kongpf8848/azure-openai-proxy)实现打字效果

**Comment by mkdirmushroom** [comment]
> > https://github.com/haibbo/cf-openai-azure-proxy
> 
> 看过了，响应的时候手动加了延迟，我自己在本地也实现了感觉不太好。目前昨天有小伙伴说是因为 Azure OpenAI 加了 Content Filter，可以申请取消。昨天已经提交了等审批后看看效果

请问大佬，申请去掉内容过滤后，stream 是逐字返回的吗？
