### ISSUE TITLE
Azure 突然可以建 GPT4的模型了，我试了下好像访问失败

### ISSUE THREAD

**Issue by zhuyaguang** [stulzq/azure-openai-proxy#27]

**Comment by stulzq** [comment]
GPT-4 我一直有在使用哦，Proxy 没问题的

**Comment by zhuyaguang** [comment]
![image](https://user-images.githubusercontent.com/8857976/235054424-d226ec2b-7aad-45ad-8b61-839154aa84ca.png)


![image](https://user-images.githubusercontent.com/8857976/235054291-1c8dd3e0-704b-427e-9098-e0b8bdd1b429.png)

这是我的配置

![image](https://user-images.githubusercontent.com/8857976/235054334-5587c080-f6e9-4130-a025-a3613058bb4a.png)

**Comment by stulzq** [comment]
需要设置一下 chatgpt-web https://github.com/stulzq/azure-openai-proxy/issues/23

**Comment by zhuyaguang** [comment]
> 需要设置一下 chatgpt-web #23

好了 多谢大佬
