### ISSUE TITLE
AZURE_OPENAI_MODEL_MAPPER 可以填多个么？

### ISSUE THREAD

**Issue by trader-tsang** [stulzq/azure-openai-proxy#28]
请问AZURE_OPENAI_MODEL_MAPPER 可以填多个么 ？ 比如
` AZURE_OPENAI_MODEL_MAPPER: gpt-3.5-turbo=gpt-35-turbo, gpt-4 = gpt4 `

**Comment by stulzq** [comment]
可以的使用英文逗号分隔：`AZURE_OPENAI_MODEL_MAPPER: gpt-3.5-turbo=gpt-35-turbo,gpt-4 = gpt4`

**Comment by trader-tsang** [comment]
好的，谢谢
