### ISSUE TITLE
如何捕获 azure-openai 域名的

### ISSUE THREAD

**Issue by irmowan** [stulzq/azure-openai-proxy#29]
Hi, 我发现Readme中，在定义 docker compose yaml file时，使用了 `OPENAI_API_BASE_URL: http://azure-openai:8080`
但是在这两个repo中都没有对这个host的捕获，请问是怎么实现这一转发的？是说docker compose里直接把 service name "azure-openai" 绑定成network里的一个host了吗？

**Comment by stulzq** [comment]
你去看看 docker compose 网络设置相关的文章
