### ISSUE TITLE
azure可以长期白嫖吗？

### ISSUE THREAD

**Issue by 102757017** [stulzq/azure-openai-proxy#3]
azure的部分服务每个月是有免费额度的，这个openai的服务每个月有没有免费的额度？还是说只能免费用一年？

**Comment by stulzq** [comment]
应该是没有的

**Comment by 102757017** [comment]
我刚刚申请了一下，不知道多久才能通过。azure在国内没有被墙，而且可以用国内的visa卡充值，相比chatgpt还是方便不少的。
