### ISSUE TITLE
大佬按照步骤部署连页面都没有

### ISSUE THREAD

**Issue by liuliu122** [stulzq/azure-openai-proxy#37]
![image](https://github.com/stulzq/azure-openai-proxy/assets/135710849/24087bec-4c20-4f3e-82fd-929375a54989)
键入服务器IP显示无法访问此页面，请问是什么情况？谢谢

**Comment by stulzq** [comment]
在服务器执行 curl localhost:3002 看看

**Comment by liuliu122** [comment]
Failed to connect to localhost port 3002: Connection refused   用的虚拟主机

**Comment by stulzq** [comment]
docker compose 贴一下

**Comment by liuliu122** [comment]
![screenshot20230607](https://github.com/stulzq/azure-openai-proxy/assets/135710849/add5ff54-033e-4563-ba7e-263009b1ae0f)

**Comment by stulzq** [comment]
应该是 docker 网络那块的问题，重装可以解决 emmm

**Comment by liuliu122** [comment]
好，谢谢大佬，我试试

**Comment by liuliu122** [comment]
大佬，重装了，还是不行   curl: (6) Could not resolve host: localhost:3002   请问还有可能是哪里出问题了？ 谢谢

**Comment by stulzq** [comment]
你这个机器环境、docker 有问题吧，这个需要你自行找解决办法了。我智能给你提供程序方面的帮助

**Comment by stulzq** [comment]
Proxy 可以直接使用二进制运行

**Comment by liuliu122** [comment]
好的，非常感谢
