### ISSUE TITLE
embedding 支持吗

### ISSUE THREAD

**Issue by WeihanLi** [stulzq/azure-openai-proxy#47]

**Comment by stulzq** [comment]
支持的

**Comment by xky-1** [comment]
> <img alt="image" width="943" src="https://private-user-images.githubusercontent.com/13200155/247127782-df6dc562-0742-4e63-8c43-e1d55419b9f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NzQxMTIsIm5iZiI6MTcxMDQ3MzgxMiwicGF0aCI6Ii8xMzIwMDE1NS8yNDcxMjc3ODItZGY2ZGM1NjItMDc0Mi00ZTYzLThjNDMtZTFkNTU0MTliOWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAzMzY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYjBlNDRkYzQ3NmFjNGRlMzM1M2MxMmU4MTA3MTVmMjNlNWJhY2EyMWUwMWEwMDBlNTc2MmE0NWFhZmM4ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.96d2tQ1dO3enxJUUHu8bgOnoBPnnAMruYeCK81v8JS4">
请求报错

**Comment by xky-1** [comment]
请求报错，是docker-compose.yml配置没配好吗？
![image](https://github.com/stulzq/azure-openai-proxy/assets/30629714/c71b338c-18e4-4d1b-b871-3816e1771541)

**Comment by WeihanLi** [comment]
看看日志里转发的 url  有没有什么错误，可能是配置 model mapping

**Comment by xky-1** [comment]
> 看看日志里转发的 url 有没有什么错误，可能是配置 model mapping
这个日志不知道在哪看，可以截个图吗， model mapping也配置了
AZURE_OPENAI_MODEL_MAPPER: gpt-3.5-turbo=lk-gpt-35-turbo,text-embedding-ada-002=lk-text-embedding-ada-002

**Comment by WeihanLi** [comment]
我之前是 model mapping 配错了，之前 docker 跑的，可以通过 docker logs 看日志，不知道是不是同一个情况

**Comment by xky-1** [comment]
感谢，看了docker logs的原生请求链接，发现没有什么问题，原来是秘钥错了，还用的chatgpt-next-web设置的密码，应该用openai_key

**Comment by xky-1** [comment]
![image](https://github.com/stulzq/azure-openai-proxy/assets/30629714/15fcbd24-e055-471e-aaa0-7efec80ebcf2)
