### ISSUE TITLE
有没有办法在openai siri的苹果快捷指令中也使用这个azure openai proxy？

### ISSUE THREAD

**Issue by TYLERCHEN999** [stulzq/azure-openai-proxy#49]
Depay刚刚被openai拒付了，正发愁无法使用openai的key了。试了一下azure-openai-proxy，很好用。
有没有办法在openai siri的苹果快捷指令中也使用这个azure openai proxy？比方这个快捷指令：https://aircode.cool/828668wg5a，目前这些快捷指令都只能设置openai的key，没法通过azure openai的api来接入。

**Comment by stulzq** [comment]
你改一下请求 OpenAI 的 API 地址改为 proxy 地址

**Comment by TYLERCHEN999** [comment]
怎么改？能否稍微细说一下？谢谢！
