### ISSUE TITLE
AZURE_OPENAI_API_VER没看太懂要怎么查

### ISSUE THREAD

**Issue by Jackiexiao** [stulzq/azure-openai-proxy#50]
README.md 中给了个链接
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/quickstart?tabs=command-line&pivots=rest-api
```
url = base_url + "/openai/deployments/" + deployment_name + "/completions?api-version=2023-05-15"
```
所以是 `AZURE_OPENAI_API_VER=2023-05-15` 吗？

**Comment by kongpf8848** [comment]
AZURE_OPENAI_API_VER目前可取的值为2023-03-15-preview、2023-05-15、2023-06-01-preview，随便使用一个就行，详细介绍可以参考：[https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/reference](https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/reference)
