### ISSUE TITLE
Can we set multiple Azure endpoints? (to increase the total TPM)

### ISSUE THREAD

**Issue by silverriver** [stulzq/azure-openai-proxy#51]
Is it  possible to set multiple Azure endpoints so that we can enjoy an increased TPM

可以挂多个Azure Endpoint吗？可以用轮询的方式分别调用这些endpoint，从而提升总的TPM。

**Comment by zsinba** [comment]
使用Nginx来进行负载分配应该是可以的，做法 是： 
启动N个azure-openai-proxy，然后使用Nginx反向代理它们；
使用基于“源地址哈希法”的Nginx分配算法，这样可以让相同的请求到同一个接口里。 

我相信这可以满足你的要求。

**Comment by silverriver** [comment]
感谢解答。这个方案666
