### ISSUE TITLE
ChatGPT error 404: {"error":{"code":"404","message": "Resource not found"}}

### ISSUE THREAD

**Issue by pjfeng** [stulzq/azure-openai-proxy#52]
您好，请教下。

我的操作基本参考您的yaml文件配置，只修改了下面4个参数。

AZURE_OPENAI_ENDPOINT: <Auzre OpenAI API Endpoint>
AZURE_OPENAI_MODEL_MAPPER: <Auzre OpenAI API Deployment Mapper>
AZURE_OPENAI_API_VER: 2023-03-15-preview
OPENAI_API_KEY: <Auzre OpenAI API Key>

改为：
environment:
OPENAI_API_KEY: 500000dedefr98999900
OPENAI_API_BASE_URL: 没改动
AUTH_SECRET_KEY: ""
MAX_REQUEST_PER_HOUR: 1000
TIMEOUT_MS: 60000

environment:
AZURE_OPENAI_ENDPOINT: myname链接
AZURE_OPENAI_MODEL_MAPPER: gpt-3.5-turbo-16k=gpt-35-turbo
AZURE_OPENAI_API_VER: 2023-05-15

结果：
网页运行了，我输入 hello，GPT 报错如下：
ChatGPT error 404: {"error":{"code":"404","message": "Resource not found"}}

麻烦各位大佬，参谋指教

**Comment by zhiCharon** [comment]
我已经按照此方法加上了OPENAI_API_MODEL，也检查了部署名，可是还是404
运行过程，我直接修改配置文件，docker compose up运行的

**Comment by kongpf8848** [comment]
2023-05-15需要加双引号，如下：
`AZURE_OPENAI_API_VER: "2023-05-15"`

**Comment by zhiCharon** [comment]
> 2023-05-15需要加双引号，如下： `AZURE_OPENAI_API_VER: "2023-05-15"`

可以了，感谢大佬。
