### ISSUE TITLE
[OpenAI] 提供错误的API密钥 | Incorrect API key provided

### ISSUE THREAD

**Issue by JackyWay** [stulzq/azure-openai-proxy#53]
各位大佬能看看配置文件哪里有问题? 提示错误的API密钥
Azure的 Model name:gpt-4-32k Model version:0314
API key和endpoint确定是正确的。

version: '3'

services:
  chatgpt-web:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY: b77000000000000000000003
      #OPENAI_API_BASE_URL: http://azure-openai:8080
      OPENAI_API_MODEL: gpt-4-32k
      AUTH_SECRET_KEY: ""
      MAX_REQUEST_PER_HOUR: 1000
      TIMEOUT_MS: 60000
    depends_on:
      - azure-openai
    links:
      - azure-openai
    networks:
      - chatgpt-ns

  azure-openai:
    image: stulzq/azure-openai-proxy
    ports:
      - 8080:8080
    environment:
      AZURE_OPENAI_ENDPOINT: https://my.openai.azure.com/
      AZURE_OPENAI_MODEL_MAPPER: gpt-4-32k-0314=gpt-4-32k
      AZURE_OPENAI_API_VER: "2023-03-14"
    networks:
      - chatgpt-ns

networks:
  chatgpt-ns:
    driver: bridge

**Comment by stulzq** [comment]
看请求日志

**Comment by JackyWay** [comment]
不好意思，请问在哪里查看请求日志？谢谢。
是不是我的配置文件docker-compose.yml没有写对？下面的docker-compose.yml版本，出现的错误则是 ChatGPT error 404: {"error":{"code":"404","message": "Resource not found"}}



version: '3'

services:
  chatgpt-web:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY: 'b77-Azure-API-KEY'
      OPENAI_API_BASE_URL: 'https://my-openai.openai.azure.com/'   //这里需要填写Azure的Endpoint吗?还是注释掉?
      OPENAI_API_MODEL: 'gpt-4-32k-0314'
      AUTH_SECRET_KEY: ""
      MAX_REQUEST_PER_HOUR: 1000
      TIMEOUT_MS: 60000
    depends_on:
      - azure-openai
    links:
      - azure-openai
    networks:
      - chatgpt-ns

  azure-openai:
    image: stulzq/azure-openai-proxy
    ports:
      - 8080:8080
    environment:
      AZURE_OPENAI_ENDPOINT: 'https://my-openai.openai.azure.com/'
      AZURE_OPENAI_MODEL_MAPPER: 'gpt-4-32k=gpt4-32'
      AZURE_OPENAI_API_VER: '0314'    //这里的的API_VER指的是?
    networks:
      - chatgpt-ns

networks:
  chatgpt-ns:
    driver: bridge

**Comment by AndyX-Net** [comment]
调试(莫关控制台)：
docker-compose -f  docker-compose.yml up


关于配置：
AZURE_OPENAI_MODEL_MAPPER 和 AZURE_OPENAI_API_VER，在这找：
![image](https://github.com/stulzq/azure-openai-proxy/assets/27819097/b0f4c62e-0de7-43bc-8d5d-c0e51efa5ef4)


AZURE_OPENAI_ENDPOINT 和 OPENAI_API_KEY，在这找: 
![image](https://github.com/stulzq/azure-openai-proxy/assets/27819097/dcadf5f7-b6f3-4c09-9a7f-c45675c9c32c)


OPENAI_API_BASE_URL: http://123.123.123.123:8080  ###你自己设定的ChatGPT-WEb的HTTP/HTTPS本地监听地址，也可用于公共访问

**Comment by github-pigsy** [comment]
按照上面的步骤部署完成后发消息会提示`ChatGPT error 404: {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}`  部署的3.5可以成功但是部署4的时候会失败，playgroup上显示版本为2023-07-01-preview。并且可以确定ebdpoint和key都是没问题的。
