### ISSUE TITLE
docker运行起来之后报DNS错误

### ISSUE THREAD

**Issue by mewho163** [stulzq/azure-openai-proxy#58]
2023/08/19 09:19:30 proxying request [] /v1/chat/completions -> https://abcde.openai.azure.com/openai/deployments/abcde/chat/completions?api-version=2023-03-15-preview
2023/08/19 09:19:40 http: proxy error: dial tcp: lookup abcde.openai.azure.com on 127.0.0.11:53: read udp 127.0.0.1:40639->127.0.0.11:53: i/o timeout

没有找到可以解决方案,请问这个可以通过配置文件解决么？

**Comment by stulzq** [comment]
尝试使用 1.3.7 版本，设置 http 代理

**Comment by kuangxiaoye** [comment]
> 尝试使用 1.3.7 版本，设置 http 代理

服务器是美西小梯子，还是会报这个错误。openai 接口都能直接调用...

**Comment by kuangxiaoye** [comment]
docker run -d -p 6003:8080 --name=azure-openai-proxy \
  --env AZURE_OPENAI_ENDPOINT=https://xxx.openai.azure.com \
  --env AZURE_OPENAI_API_VER=2023-07-01-preview \
  --env AZURE_OPENAI_MODEL_MAPPER=gpt-4=gpt-4,gpt-3.5-turbo=gpt-35-turbo \
  stulzq/azure-openai-proxy:latest

2023/10/20 13:18:48 http: proxy error: dial tcp: lookup xxx.openai.azure.com on 8.8.8.8:53: no such host


 换了服务器依然报错。。
