### ISSUE TITLE
/engines/:model/embeddings不兼容吗？

### ISSUE THREAD

**Issue by hujb2000** [stulzq/azure-openai-proxy#59]
我用langchain包的ChatOpenAI来建文档索引，关键代码段如下：
from langchain.chat_models import ChatOpenAI, AzureChatOpenAI
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.2, model_name="text-embedding-ada-002"))

在azure-openai-proxy容器服务中捕获以下日志：
[GIN] 2023/08/31 - 03:09:18 | 404 |         549ns |   192.168.160.1 | POST     "/engines/text-embedding-ada-002/embeddings"

是这个接口apiBasedRouter.Any("/engines/:model/embeddings", azure.ProxyWithConverter(templateConverter))不兼容吗

**Comment by stulzq** [comment]
同样的 issue https://github.com/stulzq/azure-openai-proxy/issues/60 ，关闭这个了
