### ISSUE TITLE
构建索引时提示：Invalid URL

### ISSUE THREAD

**Issue by hujb2000** [stulzq/azure-openai-proxy#60]
上传文件完成后构建索引时，提示Invalid URL:
INFO:openai:error_code=None error_message='Invalid URL (POST /engines/text-embedding-ada-002/embeddings)' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
error_code=None error_message='Invalid URL (POST /engines/text-embedding-ada-002/embeddings)' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
INFO:openai:error_code=None error_message='Invalid URL (POST /engines/text-embedding-ada-002/embeddings)' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
error_code=None error_message='Invalid URL (POST /engines/text-embedding-ada-002/embeddings)' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
INFO:openai:error_code=None error_message='Invalid URL (POST /engines/text-embedding-ada-002/embeddings)' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
error_code=None error_message='Invalid URL (POST /engines/text-embedding-ada-002/embeddings)' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
INFO:openai:error_code=None error_message='Invalid URL (POST /engines/text-embedding-ada-002/embeddings)' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
error_code=None error_message='Invalid URL (POST /engines/text-embedding-ada-002/embeddings)' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False

**Comment by stulzq** [comment]
目前支持 /v1/embeddings，不支持  /engines/text-embedding-ada-002/embeddings

**Comment by stulzq** [comment]
试一下指定镜像版本 v1.3.5
