### ISSUE TITLE
ChatGPT error 404

### ISSUE THREAD

**Issue by JackieHeCc** [stulzq/azure-openai-proxy#62]
用docker compose搭建到vps之后访问页面，对话返回：
ChatGPT error 404: {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

请问这是yml里面的配置不对导致的吗？有没有大神指导一下。

**Comment by stulzq** [comment]
<img width="1078" alt="image" src="https://github.com/stulzq/azure-openai-proxy/assets/13200155/a51627bc-2f2e-4eef-a4fd-21d5ff45e118">

**Comment by JackieHeCc** [comment]
> <img alt="image" width="1078" src="https://user-images.githubusercontent.com/13200155/268547718-a51627bc-2f2e-4eef-a4fd-21d5ff45e118.png">

我的设置是这样子的没错，问题依然存在。

**Comment by stulzq** [comment]
你的 配置发一下，然后 azure 截个图

**Comment by stulzq** [comment]
还有最简单的方法自己手动调azure api，如果也是404那么就考虑重新创建，或者连续 azure openai。如果调用正常但是通过proxy404了，那么百分百是你配置不对。

**Comment by JackieHeCc** [comment]
> 还有最简单的方法自己手动调azure api，如果也是404那么就考虑重新创建，或者联系 azure openai。如果调用正常但是通过proxy 404了，那么百分百是你配置不对。

手动将配置加入setting可以访问，通过docker compse就不行，很奇怪，配置截图如下：
![微信截图_20230918151608](https://github.com/stulzq/azure-openai-proxy/assets/126449980/7b4c1eda-b553-4623-b273-5d81fbe0ce81)

这个配置是我换Yidadaa的GPT-Next-Web的，提示跟chatgpt-web有所不同，这个提示：
{
  "error": {
    "message": "Incorrect API key provided: 7c4c6662********************56b8. You can find your API key at https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
}

**Comment by stulzq** [comment]
设置 OPENAI_API_MODEL，具体的到 chatgpt-web 看一下，这边只处理 proxy 的问题。

**Comment by JackieHeCc** [comment]
> 设置 OPENAI_API_MODEL，具体的到 chatgpt-web 看一下，这边只处理 proxy 的问题。

好的，感谢，昨天用Vercel部署成功了，需要在部署的时候就把变量Env设置好，而不是部署好之后再添加变量，之前记得可以，不知道现在怎么不行了，还是非常感谢。

**Comment by stulzq** [comment]
好的
