### ISSUE TITLE
在配置后，进不去nginx的管理页面及无法通过之前使用nginx反代后的chatweb域名访问，只能通过ip访问

### ISSUE THREAD

**Issue by fysxaki** [stulzq/azure-openai-proxy#64]
今天修改之前，均正常访问，应用这个项目改变我的yml文件之后，出现了问题。具体表现为访问我的域名之后，会有一个报错，主要信息为HTTP 502，问chatgpt后，给出的办法均无法恢复，nginx服务器运行了但是管理系统进不去，以及nginx设置的代理也全部失效，现在通过ip+端口的方式在访问我自己的chatweb。
我的应对有
1.检查nginx防火墙的状态是inactive
2.sudo nginx -t自己检查配置文件给出的反馈也都正常，
3.错误日志停留在几个小时之前，里面是80端口被占用，我也已经全部停止，而后重启，并没有解决这个问题。
在后面看到配置文件中涉及到了networks，想到了有没有可能是这方面网络没有配置的原因。
[新建文本文档 (2).txt](https://github.com/stulzq/azure-openai-proxy/files/12646132/2.txt)
我的文件中将域名替换为了xxx，
如果您有时间可以提提大概的改正方向，多谢！

**Comment by stulzq** [comment]
只处理 Proxy 的问题
