### ISSUE TITLE
大佬 是不是其他类似的应用都可以用这个proxy了

### ISSUE THREAD

**Issue by zhuyaguang** [stulzq/azure-openai-proxy#7]
比如著名的 https://github.com/mckaywrigley/chatbot-ui 也可以用了吧

**Comment by stulzq** [comment]
我看了一下，需要更换 API 地址为 Proxy 的地址，但是这个项目的 README 没有写相关的设置。

发现这个 issue: https://github.com/mckaywrigley/chatbot-ui/issues/312

可以尝试一下通过这个环境变量来设置 OPENAI_API_HOST
