### ISSUE TITLE
请问大佬有没有支持whisper模型的计划？

### ISSUE THREAD

**Issue by oudexin** [stulzq/azure-openai-proxy#71]
azure也放出了whisper模型，如果能支持的话，像opencat类的app也就可以语音对话了。
相关文档：
https://learn.microsoft.com/zh-cn/azure/ai-services/openai/reference#speech-to-text

**Comment by stulzq** [comment]
看了下我还没有权限创建这个模型，木有办法测试 emmm

**Comment by oudexin** [comment]
目前可用区：美国中北部和西欧，大佬可以再看看。

**Comment by stulzq** [comment]
试了下创建成功啦，下周更新，这周暂时没时间

**Comment by oudexin** [comment]
> 试了下创建成功啦，下周更新，这周暂时没时间

大佬辛苦啦
