### ISSUE TITLE
端口自定义问题

### ISSUE THREAD

**Issue by h88782481** [stulzq/azure-openai-proxy#72]
当我吧azure-openai-proxy的端口从8080改为别的端口后会出现connect ECONNREFUSED
version: '3'

services:
  chatgpt-web:
    image: yidadaa/chatgpt-next-web
    container_name: chatgpt-web
    ports:
      - 3001:3000
    environment:
      OPENAI_API_KEY: xxx
      BASE_URL: http://azure-openai:8111
      CODE: ""
      HIDE_USER_API_KEY: 1
      HIDE_BALANCE_QUERY: 1
    depends_on:
      - azure-openai
    links:
      - azure-openai
    networks:
      - chatgpt-ns

  azure-openai:
    image: stulzq/azure-openai-proxy
    container_name: azure-openai
    ports:
      - 8111:8080
    environment:
      AZURE_OPENAI_ENDPOINT: https://xxx.openai.azure.com/
      AZURE_OPENAI_MODEL_MAPPER: gpt-3.5-turbo=xxx,gpt-4=xxx
      AZURE_OPENAI_API_VER: 2023-07-01-preview
    networks:
      - chatgpt-ns

networks:
  chatgpt-ns:
    driver: bridge
这个是我改的docker compose只要把映射端口从8080改为其他端口就会出现connect ECONNREFUSED
这个有办法解决吗？

**Comment by GreatAsia** [comment]
你解决这个问题了吗?我也遇到这个问了

**Comment by h88782481** [comment]
> 你解决这个问题了吗?我也遇到这个问了

之前我忘了，docker里的自定义网络是通过内网端口访问的，跟映射端口没关系，docker访问用8080就行，外部映射的端口该用啥就用啥

**Comment by tinet-jutt** [comment]
你解决这个问题了吗?我也遇到这个问了
