### ISSUE TITLE
API Call is not working

### ISSUE THREAD

**Issue by lzhgus** [stulzq/azure-openai-proxy#9]
可能是一个非常小白的问题， 我跑了docker之后， 直接curl call api，得到一下结果，是我配置漏了哪一步吗？ 谢谢！

<img width="599" alt="image" src="https://user-images.githubusercontent.com/5875125/230501150-e9b396a6-185c-4105-aa42-cbc1ca52bb35.png">

{"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

**Comment by Cabbage-Leon** [comment]
你好，我也有同样的问题，是因为AZURE_OPENAI_MODEL_MAPPER不对还是什么原因？@lzhgus
